In [2]:
import pandas as pd

In [3]:
data= pd.read_html('https://www.twse.com.tw/fund/TWT44U?response=html&date=20200311')  
data[0]

    109年03月11日 投信買賣超彙總表
     Unnamed: 0_level_1  證券代號   證券名稱     買進股數  賣出股數    買賣超股數
0                   NaN  2368    金像電  2700000     0  2700000
1                   NaN  2603     長榮  2434000     0  2434000
2                   NaN  3017     奇鋐  1995000     0  1995000
3                   NaN  4746     台耀  1594000     0  1594000
4                   NaN  3037     欣興  1059000  2000  1057000
..                  ...   ...    ...      ...   ...      ...
119                 NaN  2301    光寶科        0  5000    -5000
120                 NaN  6166     凌華        0  5000    -5000
121                 NaN  6451  訊芯-KY        0  4000    -4000
122                 NaN  2327     國巨      488  3000    -2512
123                 NaN  6176     瑞儀        0  1000    -1000

[124 rows x 6 columns]

In [37]:
data=pd.read_html('https://www.cnyes.com/twstock/a_QFII9.aspx')
data[0]
# data[1]賣超

        買超
        代碼         名稱   買超張數     持股張數   持股率%
0   00677U      富邦VIX  47517  1001447  28.45
1     2603         長榮   8023  1136492  23.61
2     2412        中華電   7116  1273645  16.41
3     6116         彩晶   6769   353032  11.26
4     2881        富邦金   5833  2706621  26.44
5     2323         中環   5125   103015   8.88
6     2448         晶電   4515   197412  18.13
7     1314        中石化   4226   537577  16.36
8     2344        華邦電   4208   898589  22.57
9   00634R     富邦上証反1   3907     6738   3.79
10    4904         遠傳   3235   693073  21.26
11  00638R  元大滬深300反1   3104    16914  17.35
12    6153        嘉聯益   2538    73668  13.53
13    2498        宏達電   2365   132044  16.12
14    2104       國際中橡   2349   117717  11.95
15    2368        金像電   2336    54719  10.01
16    3016         嘉晶   2296     5118   1.86
17    2371         大同   2035   923281  39.46
18    9958        世紀鋼   1990    11073   5.28
19    2478         大毅   1895    11913   8.20
20    2618        長榮航   1822  1359382  28.00
21    3704        合勤控   1761    45971  10.42
22    2605         新興   1750   194744  33.26
23    2342         茂矽   1675    11496   7.35
24    2360         致茂   1664   268315  64.02
25    8046         南電   1643    43717   6.76
26    3338         泰碩   1630     3904   4.51
27    8215        明基材   1628     7917   2.46
28    6230         超眾   1534    54785  63.44
29    3545         敦泰   1491    70093  23.40

In [10]:
# 1.Series
# 1.1 建立 Series

# 資料可以的類型如下：

# 單一資料
# array
# dictionary


import pandas as pd # 引用套件並縮寫為 pd
select = pd.Series(data, index = idx) #將資料讀入 series 方法中

In [12]:
# ❖ 資料為單一資料
import pandas as pd

cars = "BENZ"  
select = pd.Series(cars, index = range(3))  
print(select)

0    BENZ
1    BENZ
2    BENZ
dtype: object

In [9]:
# ❖ 資料為 Array
import pandas as pd  # 引用套件並縮寫為 pd

cars = ["BMW", "BENZ", "Toyota", "Nissan", "Lexus"]

select = pd.Series(cars)  
print(select)

0       BMW
1      BENZ
2    Toyota
3    Nissan
4     Lexus
dtype: object

In [ ]:
# ❖ 資料為 Dictionary
# ❖ 資料選擇與篩選
# 可以針對 dict 或是 array 資料透過透過索引值或標籤，挑選出你所要的值。
dict = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict, index = dict.keys()) # 排序與原 dict 相同,可省略index=dict.keys()
print(select[0])  
print("=====")  
print(select['sensor1'])  
print("=====")  
print(select[[0, 2, 4]])  
print("=====")  
print(select[['factory', 'sensor1', 'sensor3']])

In [6]:
# ❖ 資料切片
# 透過透過索引值或標籤，切割需要的值
dict = {  
    "factory": "Taipei",
    "sensor1": "1",
    "sensor2": "2",
    "sensor3": "3",
    "sensor4": "4",
    "sensor5": "5"
}

select = pd.Series(dict, index = dict.keys()) # 排序與原 dict 相同  
print(select[:2])  
print("=====")  
print(select['sensor2':])

factory    Taipei
sensor1         1
dtype: object
=====
sensor2    2
sensor3    3
sensor4    4
sensor5    5
dtype: object

In [14]:
# 2.DataFrame
# 2.1 建立 DataFrame
# DataFrame 用來處理結構化(Table like)的資料，有列索引與欄標籤的二維資料集
# 可以透過 Dictionary 或是 Array 來建立，但也可以利用外部的資料來讀取後來建立，例如： CSV 檔案、資料庫等等。

# 下列範例會介紹利用 Dictionary 或是 Array 來建立，並使用 DataFrame 的方法來操作資料查看、資料篩選、資料切片、資料排序等運算。

In [16]:
# ❖ 資料為 Dictionary

import pandas as pd # 引用套件並縮寫為 pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
       }

select_df = pd.DataFrame(dict)

print(select_df) # 看看資料框的外觀

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58

In [26]:
# test
dict1={'stock':['1','2','3'],
       "closed price":['a','b','c']
      }
select_pd=pd.DataFrame(dict1)
print(select_pd)

  stock closed price
0     1            a
1     2            b
2     3            c

In [17]:
# ❖ 資料為 Array

import pandas as pd

arr = groups = [["Movies", 46],["Sports", 8], ["Coding", 12], ["Fishing",12], ["Dancing",6], ["cooking",8]]

df = pd.DataFrame(arr, columns = ["name", "num"]) # 指定欄標籤名稱  
print(df)

      name  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking    8

In [ ]:
# 2.2 DataFrame 的操作
# ❖ 資料描述查看
# 可以透過下列方法查看目前資料的資訊

# .shape
# .describe()
# .head()
# .tail()
# .columns
# .index
# .info()

In [29]:
# Pandas 的 data frame 資料結構有一些方法或屬性

import pandas as pd

groups = ["Movies", "Sports", "Coding", "Fishing", "Dancing", "cooking"]  
num = [46, 8, 12, 12, 6, 58]

dict = {"groups": groups,  
        "num": num
        }


select_df = pd.DataFrame(dict)
print(select_df)
print('---')
print(select_df.shape,'# 回傳列數與欄數'  )
print("---")  
print(select_df.describe(),'# 回傳描述性統計' ) 
print("---")  
print(select_df.head(3),'# 回傳前三筆觀測值'  )
print("---")  
print(select_df.tail(3),'# 回傳後三筆觀測值'  )
print("---")  
print(select_df.columns,'# 回傳欄位名稱' )
print("---")  
print(select_df.index,'# 回傳 index' )
print("---")  
print(select_df.info,'# 回傳資料內容'  )

    groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58
---
(6, 2) # 回傳列數與欄數
---
             num
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000 # 回傳描述性統計
---
   groups  num
0  Movies   46
1  Sports    8
2  Coding   12 # 回傳前三筆觀測值
---
    groups  num
3  Fishing   12
4  Dancing    6
5  cooking   58 # 回傳後三筆觀測值
---
Index(['groups', 'num'], dtype='object') # 回傳欄位名稱
---
RangeIndex(start=0, stop=6, step=1) # 回傳 index
---
<bound method DataFrame.info of     groups  num
0   Movies   46
1   Sports    8
2   Coding   12
3  Fishing   12
4  Dancing    6
5  cooking   58> # 回傳資料內容

In [31]:
# ❖ 資料選擇與篩選
# 可以透過下列方法選擇元素

# 中括號 [] 選擇元素
# . 將變數當作屬性選擇
# .loc .iloc 方法選擇
# 使用布林值篩選